// lib/transcript-service.ts
import { YoutubeTranscript } from "youtube-transcript";
import { safeLog } from "./logger";

export class TranscriptService {
  async getTranscript(videoId: string): Promise<string[]> {
    try {
      const { segments } = await this.fetchTranscriptWithFallback(videoId);
      return segments.map((segment) => segment.text);
    } catch (error) {
      safeLog("error", `Error fetching transcript for video ${videoId}:`, error.message);
      throw error;
    }
  }

  async getTranscriptWithTimestamps(
    videoId: string
  ): Promise<{ segments: YoutubeTranscript.Transcript[], language: string }> {
    try {
      return await this.fetchTranscriptWithFallback(videoId);
    } catch (error) {
      safeLog("error", `Error fetching transcript with timestamps for video ${videoId}:`, error.message);
      throw error;
    }
  }

  async getBatchTranscripts(
    videoIds: string[]
  ): Promise<Map<string, string[]>> {
    const transcripts = new Map<string, string[]>();
    for (const videoId of videoIds) {
      try {
        const transcript = await this.getTranscript(videoId);
        transcripts.set(videoId, transcript);
      } catch (error) {
        safeLog("error", `Skipping transcript for video ${videoId}:`, error.message);
        transcripts.set(videoId, []);
      }
    }
    return transcripts;
  }

  private async fetchTranscriptWithFallback(videoId: string): Promise<{ segments: YoutubeTranscript.Transcript[], language: string }> {
    const preferredLanguages = ["en", "hi", "es", "fr", "de", "ja"];
    const autoGeneratedLanguages = preferredLanguages.map(lang => `a.${lang}`);
    const allLanguages = [...new Set([...preferredLanguages, ...autoGeneratedLanguages])];
    let lastError: Error | null = null;
    let availableLanguages: string[] = [];

    safeLog("error", `[DEBUG] Starting transcript fetch for ${videoId} with languages: ${allLanguages.join(", ")}`);

    // Try all languages with custom user agent
    for (const lang of allLanguages) {
      try {
        safeLog("error", `[DEBUG] Attempting to fetch transcript for ${videoId} in language: ${lang}`);
        const transcript = await YoutubeTranscript.fetchTranscript(videoId, {
          lang,
          customUserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        });
        if (transcript.length > 0) {
          safeLog("error", `[DEBUG] Successfully fetched transcript for ${videoId} in language: ${lang} with ${transcript.length} segments`);
          return { segments: transcript, language: lang };
        } else {
          safeLog("error", `[DEBUG] No segments found for ${videoId} in language: ${lang}, trying auto-detection`);
          // Try auto-detection without lang
          const autoTranscript = await YoutubeTranscript.fetchTranscript(videoId, {
            customUserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
          });
          if (autoTranscript.length > 0) {
            safeLog("error", `[DEBUG] Successfully fetched transcript for ${videoId} via auto-detection with ${autoTranscript.length} segments`);
            return { segments: autoTranscript, language: "auto" };
          }
        }
      } catch (error) {
        lastError = error;
        const errorMessage = error.message || "";
        safeLog("error", `[DEBUG] Failed transcript for ${videoId} in ${lang}: ${errorMessage}`);
        if (errorMessage.includes("Available languages:")) {
          const match = errorMessage.match(/Available languages: ([\w\s,]+)$/);
          if (match) {
            availableLanguages = match[1].split(", ").map(lang => lang.trim());
            safeLog("error", `[DEBUG] Detected available languages: ${availableLanguages.join(", ")}`);
          }
        }
      }
    }

    // Fallback to available languages
    if (availableLanguages.length > 0) {
      safeLog("error", `[DEBUG] Falling back to available languages: ${availableLanguages.join(", ")}`);
      for (const lang of availableLanguages) {
        if (!allLanguages.includes(lang)) {
          try {
            safeLog("error", `[DEBUG] Attempting fallback transcript for ${videoId} in language: ${lang}`);
            const transcript = await YoutubeTranscript.fetchTranscript(videoId, {
              lang,
              customUserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            });
            if (transcript.length > 0) {
              safeLog("error", `[DEBUG] Successfully fetched transcript for ${videoId} in language: ${lang} with ${transcript.length} segments`);
              return { segments: transcript, language: lang };
            }
          } catch (error) {
            lastError = error;
            safeLog("error", `[DEBUG] Failed fallback transcript for ${videoId} in ${lang}: ${error.message}`);
          }
        }
      }
    }

    // Final attempt with auto-detection
    try {
      safeLog("error", `[DEBUG] Final attempt with auto-detection for ${videoId}`);
      const autoTranscript = await YoutubeTranscript.fetchTranscript(videoId, {
        customUserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      });
      if (autoTranscript.length > 0) {
        safeLog("error", `[DEBUG] Successfully fetched transcript for ${videoId} via final auto-detection with ${autoTranscript.length} segments`);
        return { segments: autoTranscript, language: "auto" };
      }
    } catch (error) {
      lastError = error;
      safeLog("error", `[DEBUG] Failed final auto-detection for ${videoId}: ${error.message}`);
    }

    safeLog("error", `[DEBUG] No transcript available for ${videoId} after trying all languages. Available languages: ${availableLanguages.length ? availableLanguages.join(", ") : "none"}`);
    throw new Error(`No transcript available for video ${videoId} in any supported language: ${lastError?.message || "Unknown error"}`);
  }
}